# Generated by Django 4.1.9 on 2023-06-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('numeroId', models.IntegerField()),
                ('fechaNacimiento', models.DateTimeField()),
                ('fechaCreacion', models.DateTimeField()),
            ],
        ),
    ]
